package sprout.util;

public enum RC
{
	SUCCESS,
	NOT_YET_IMPLEMENTED,
	GENERIC_ERROR,
	IO_ERROR,
	TREE_INVALID_BUCKET_INDEX,
	TREE_INVALID_SLOT_INDEX,
	TREE_PUSH_DOWN_ERROR,
	TREE_INVALID_PATH_LENGTH,
	INVALID_TUPLE_SIZE,
	INVALID_BUCKET_SIZE,
	UNDEFINED_ERROR;
}
