tau: 3					# tau in the write-up
nBits: 12				# bits of N in the record
w: 4					# number of tuples in each bucket
e: 4 					# number of buckets contained in each leaf
dBytes: 4 				# record D bytes in the last tree
insert: 1000			# number of records to be initially inserted (-1 means insert max number)