# small sample configuration to get everything working as expected
# we'll scale up when ready

# tree fanout (we assume binary tree, so make this 2)
fanout: 2 

# levels in ORAM hierarchy
levels: 2

# number of buckets contained in each leaf
leafExpansion: 4

# this is tau, basically, it corresponds to the number of sub-tree leaves encoded in the leaf nodes of each non-base tree
tau: 8

# size of the virtual address space taking leaf expansion into account == 2^k (k >= 2), so k = log(this number)
addressSpace: 128

# parameters for the base tree
tupleBitsN: 9
tupleBitsL: 9
bucketDepth: 4
dataSize: 5 # bytes?
